version: '3'
services:
  nginx:
    image: "thijsferyn/nginx:primary"
    container_name: sflive-nginx
    hostname: nginx
    volumes:
    -  ./:/var/www/html
    ports:
     - "8080:80"  
    depends_on:
      - "php"
  php:
    image: "thijsferyn/php:primary"
    restart: always
    container_name: sflive-php
    hostname: php
    volumes:
    -  ./:/var/www/html
    ports:
     - "9000:9000"
  varnish:
    image: "thijsferyn/varnish:primary"
    container_name: sflive-varnish
    hostname: varnish
    volumes:
      -  ./default.vcl:/etc/varnish/default.vcl
    ports:
     - "6080:6080"
     - "6081:6081"
     - "6082:6082"
     - "6083:6083"
    environment:
    - BACKEND=nginx
    depends_on:
      - "nginx"
  haproxy:
    image: "thijsferyn/haproxy:latest"
    container_name: sflive-haproxy
    hostname: haproxy
    environment:
      - SYSLOGD=1
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - "varnish"