version: '3'
services:
  nginx:
    image: "thijsferyn/nginx:primary"
    container_name: sflive-nginx
    hostname: nginx
    volumes:
    -  ./:/var/www/html
    ports:
     - "8080:80"  
    depends_on:
      - "php"  
  nginx2:
    image: "thijsferyn/nginx:secondary"
    container_name: sflive-nginx2
    hostname: nginx2
    volumes:
    -  ./:/var/www/html
    ports:
     - "8081:80"           
    depends_on:
      - "php2"    
  php:
    image: "thijsferyn/php:primary"
    restart: always
    container_name: sflive-php
    hostname: php
    volumes:
    -  ./:/var/www/html
    ports:
     - "9000:9000"
  php2:
    image: "thijsferyn/php:secondary"
    restart: always
    container_name: sflive-php2
    hostname: php2
    volumes:
    -  ./:/var/www/html
    ports:
     - "9001:9000"
  varnish:
    image: "thijsferyn/varnish:primary"
    container_name: sflive-varnish
    hostname: varnish
    volumes:
      -  ./default.vcl:/etc/varnish/default.vcl
    ports:
     - "6080:6080"
     - "6081:6081"
     - "6082:6082"
     - "6083:6083"
    environment:
    - BACKEND=nginx
    - SERVER=primary
    depends_on:
      - "nginx"
      - "nginx2"
  varnish2:
    image: "thijsferyn/varnish:secondary"
    container_name: sflive-varnish2
    hostname: varnish2
    volumes:
      -  ./default.vcl:/etc/varnish/default.vcl
    ports:
     - "6084:6080"
     - "6085:6081"
     - "6086:6082"
     - "6087:6083"
    environment:
    - BACKEND=nginx2
    - SERVER=secondary
    depends_on:
      - "nginx"
      - "nginx2"    
  haproxy:
    image: "thijsferyn/haproxy:latest"
    container_name: sflive-haproxy
    hostname: haproxy
    environment:
      - SYSLOGD=1
    ports:
     - "80:80"
     - "443:443"
    depends_on:
      - "varnish"
      - "varnish2"